{
 "title": "Synology SNMP DashBoard",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "query_result(sum by (instance)(ifInOctets{job=\"snmp\"}))"
   },
   {
    "name": "Interface",
    "query": "query_result(ifInOctets{job=\"snmp\",instance=\"$Device\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Trafick of $Interface Interfaces",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "repeat": "Interface",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m])  or irate(ifInOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m])  or irate(ifOutOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "systemFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "systemFanStatus" }
   ]
  },
  {
   "title": "cpuFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "cpuFanStatus" }
   ]
  },
  {
   "title": "systemStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "systemStatus" }
   ]
  },
  {
   "title": "powerStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "powerStatus" }
   ]
  },
  {
   "title": "raidStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "raidStatus" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "laLoadInt" }
   ]
  }
 ]
}