{
 "title": "Loki / Deletion bossjones",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(loki_build_info, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(loki_build_info{instance=~\"$instance\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Pending Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_compactor_pending_delete_requests_count{instance=~\"$instance\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Oldest Pending Request Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(loki_compactor_oldest_pending_delete_request_age_seconds{instance=~\"$instance\", job=~\"$job\"})"
    }
   ]
  },
  { "title": "Churn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Delete Requests Received / Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_received_total{instance=~\"$instance\", job=~\"$job\"}[1d]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Delete Requests Processed / Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_processed_total{instance=~\"$instance\", job=~\"$job\"}[1d]))",
     "legendFormat": "processed"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Failures in Loading Delete Requests / Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_load_pending_requests_attempts_total{status=\"fail\", instance=~\"$instance\", job=~\"$job\"}[1h]))",
     "legendFormat": "failures"
    }
   ]
  }
 ]
}