{
 "title": "Loki:AccessLogs",
 "description": "Loki dashboards for promtail metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "datasource", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "HTTP_status_200",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s200\\\\s\" [15m] )"
    }
   ]
  },
  {
   "title": "HTTP_status_302",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s302\\\\s\" [15m] )"
    }
   ]
  },
  {
   "title": "HTTP_status_404",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"\\\\s404\\\\s\" [15m])"
    }
   ]
  },
  {
   "title": "error_log",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"error\" [15m])"
    }
   ]
  },
  {
   "title": "302_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s302\\\\s\""
    }
   ]
  },
  {
   "title": "404_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"\\\\s404\\\\s\""
    }
   ]
  },
  {
   "title": "error_Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"error\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}