{
 "title": "Loki / Chunks bossjones",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(loki_build_info, instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(loki_build_info{instance=~\"$instance\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Active Series / Chunks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{instance=\"$instance\", job=\"loki\"})",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Chunks per series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{instance=\"$instance\", job=\"loki\"}) / sum(loki_ingester_memory_streams{instance=\"$instance\", job=\"loki\"})",
     "legendFormat": "chunks"
    }
   ]
  },
  { "title": "Flush Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_utilization_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_utilization_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_utilization_sum{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_utilization_count{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_age_seconds_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_age_seconds_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_age_seconds_sum{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) * 1e3 / sum(rate(loki_ingester_chunk_age_seconds_count{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Flush Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Log Entries Per Chunk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_entries_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_entries_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_entries_sum{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_entries_count{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Index Entries Per Chunk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_index_entries_per_chunk_sum{instance=\"$instance\", job=\"loki\"}[5m])) / sum(rate(loki_chunk_store_index_entries_per_chunk_count{instance=\"$instance\", job=\"loki\"}[5m]))",
     "legendFormat": "Index Entries"
    }
   ]
  },
  { "title": "Flush Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length{instance=\"$instance\", job=\"loki\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_ingester_chunk_age_seconds_count{instance=\"$instance\", job=\"loki\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Flush Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Chunks Flushed/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_flushed_total{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chunk Flush Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Chunk Utilization",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Chunk Size Bytes",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{instance=\"$instance\", job=\"loki\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Chunk Size Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_size_bytes_bucket{instance=\"$instance\", job=\"loki\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(loki_ingester_chunk_size_bytes_bucket{instance=\"$instance\", job=\"loki\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_size_bytes_bucket{instance=\"$instance\", job=\"loki\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Chunk Duration hours (end-start)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(loki_ingester_chunk_bounds_hours_bucket{instance=\"$instance\", job=\"loki\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_bounds_hours_bucket{instance=\"$instance\", job=\"loki\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_bounds_hours_sum{instance=\"$instance\", job=\"loki\"}[5m])) / sum(rate(loki_ingester_chunk_bounds_hours_count{instance=\"$instance\", job=\"loki\"}[5m]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}