{
 "title": "Performance Overview - Grafana",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [
  "grafana",
  "prometheus",
  "performance_overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"grafana\"},instance)"
    }
   },
   {
    "name": "datasource",
    "label": "Datesource",
    "query": {
     "query": "label_values({job=~\"grafana\"},datasource)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(grafana_build_info,version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Grafana Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(1, grafana_info or grafana_build_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Organization Count",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Playlist Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_total_playlists" }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (instance)(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} Resident Mem"
    },
    {
     "expr": "avg by (instance)(process_virtual_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Grafana Performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"grafana\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (statuscode) (irate(http_request_total{job='grafana'}[5m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests By Routing Group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  { "title": "Data Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Response Time By Datasource",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (datasource) (rate(grafana_datasource_request_duration_seconds{instance=~\"$instance\", datasource=~\"$datasource\"}[$__rate_interval])) * 1000",
     "legendFormat": "Datasource {{datasource}}"
    }
   ]
  },
  {
   "title": "Requests By Datasource",
   "type": "timeseries",
   "description": "grafana_datasource_request_total",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datasource) (rate(grafana_datasource_request_total{instance=~\"$instance\", datasource=~\"$datasource\"}[$__rate_interval]))",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Response Size By Datasource",
   "type": "timeseries",
   "description": "grafana_datasource_response_size_bytes_sum",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (datasource) (rate(grafana_datasource_response_size_bytes_sum{instance=~\"$instance\", datasource=~\"$datasource\"}[$__rate_interval]))",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  { "title": "Response Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(grafana_api_response_status_total{instance=~\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "rate(grafana_page_response_status_total{instance=~\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "rate(grafana_proxy_response_status_total{instance=~\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "timeseries",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_login_post_total{instance=~\"$instance\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{instance=~\"$instance\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp Details",
   "type": "timeseries",
   "description": "http request counter",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_request_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "timeseries",
   "description": "summary for dataproxy request duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Avg (5 min)",
   "type": "timeseries",
   "description": "average dataproxy request duration over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{instance=~\"$instance\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "Average Requests Duration"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg (5 min)",
   "type": "timeseries",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{instance=~\"$instance\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg (5 min)",
   "type": "timeseries",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{instance=~\"$instance\"}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg (5 min)",
   "type": "timeseries",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{instance=~\"$instance\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}