#TODO: Uses some of this https://zeigren.com/posts/monitoring_prometheus_loki/
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout:     1m
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
# scrape_configs:
#   - job_name: 'unifipoller'
#     scrape_interval: 30s
#     static_configs:
#       - targets:
#         - https://unifi.controller:8443
#         - https://another.controller:8443
#     metrics_path: /scrape
#     relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: localhost:9130
# *********************************************************
# Replace localhost with the IP of your unpoller host, and replace unifi.controller and another.controller with the IPs of your controllers.
# *********************************************************
scrape_configs:
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
      - targets:
        - https://192.168.1.150:8443
    metrics_path: /scrape
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.1.98:9130
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        - targets: ['192.168.1.98:9090']

  - job_name: 'node-exporter'
    metrics_path: /metrics

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        - targets: ['192.168.1.98:9100']

  - job_name: 'loki'
    metrics_path: /metrics

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        - targets: ['192.168.1.98:3100']

  - job_name: 'promtail'
    metrics_path: /metrics

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        - targets: ['192.168.1.98:9080']

  # # DISABLED IN FAVOR OF NETDATA
  # - job_name: cadvisor # Local container metrics
  #   # https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
  #   static_configs:
  #     - targets:
  #         - cadvisor:8081 # Can use the service name of a container to connect to it if containers are on the same network
  #       labels:
  #         host: 192.168.1.98 # Add hostname label to make it easier to differentiate machines
  #   metric_relabel_configs:
  #     # Change the name from swarmstack_container.1.xxxx to swarmstack_container
  #     - source_labels: [container_label_com_docker_swarm_service_name]
  #       target_label: name
  #       # Only keep data that is used in graphs to reduce size
  #     - source_labels: [__name__]
  #       regex: container_last_seen|container_memory_usage_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_fs_reads_bytes_total|container_fs_writes_bytes_total|container_cpu_usage_seconds_total|container_start_time_seconds
  #       action: keep
  #       # Only keep necessary labels to keep things neat and reduce size
  #     - regex: Time|__name__|container_label_com_docker_stack_namespace|instance|job|name|interface|device|Value.*|host
  #       action: labelkeep

  - job_name: traefik # Network metrics for internet facing services
    # https://doc.traefik.io/traefik/observability/metrics/overview/
    static_configs:
      - targets:
          - traefik:8080
        labels:
          host: 192.168.1.98
    metric_relabel_configs:
      # Only keep data that is used in graphs to reduce size
      - source_labels: [__name__]
        regex: traefik_service_requests_total|traefik_service_request_duration_seconds_sum|traefik_service_request_duration_seconds_count
        action: keep

  - job_name: 'netdata'

    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus ]

    static_configs:
      - targets: ['192.168.1.98:19999']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - blackbox:9115    # Target to probe with http.
    #     # - http://prometheus.io    # Target to probe with http.
    #     # - https://prometheus.io   # Target to probe with https.
    #     - http://24.193.239.148:18000 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  # NOTE: https://prometheus.io/docs/guides/multi-target-exporter/
  # To fix this, we will use relabeling. Relabeling is useful here because behind the scenes many things in Prometheus are configured with internal labels. The details are complicated and out of scope for this guide. Hence we will limit ourselves to the necessary. But if you want to know more check out this talk. For now it suffices if you understand this:

  # All labels starting with __ are dropped after the scrape. Most internal labels start with __.
  # You can set internal labels that are called __param_<name>. Those set URL parameter with the key <name> for the scrape request.
  # There is an internal label __address__ which is set by the targets under static_configs and whose value is the hostname for the scrape request. By default it is later used to set the value for the label instance, which is attached to each metric and tells you were the metrics came from.

  - job_name: 'cerebro-exporter'
    metrics_path: /metrics
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 'http://192.168.1.164:18000' # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        # Target: This allows you to use a relabel_config object to select targets to scrape and relabel metadata created by any service discovery mechanism.
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.98:9115  # The blackbox exporter's real hostname:port.
        # replacement: 192.168.1.102:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'ping'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #third state whether this is testing external or internal network
        target_label: routing
        replacement: $3
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #fourth is which switch/router the device is connected to.
        target_label: switching
        replacement: $4
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        # replacement: 192.168.1.102:9115  # The blackbox exporter's real hostname:port.
        replacement: 192.168.1.98:9115  # The blackbox exporter's real hostname:port.
