# -*- coding: utf-8 -*-
# SOURCE: https://github.com/autopilotpattern/jenkins/blob/master/makefile
MAKEFLAGS += --warn-undefined-variables
# .SHELLFLAGS := -eu -o pipefail

# SOURCE: https://github.com/luismayta/zsh-servers-functions/blob/b68f34e486d6c4a465703472e499b1c39fe4a26c/Makefile
# Configuration.
SHELL = /bin/bash
ROOT_DIR = $(shell pwd)

MAKE := make

gpr:
	git pull --rebase

restart:
	docker compose --env-file env -d restart pushgateway
	docker compose --env-file env -d restart prometheus && \
	docker compose --env-file env -d restart loki-write && \
	docker compose --env-file env -d restart loki-read && \
	docker compose --env-file env -d restart loki-backend && \
	docker compose --env-file env -d restart grafana && \
	docker compose --env-file env -d restart promtail && \
	docker compose --env-file env -d restart grafana && \
	docker compose --env-file env -d restart minio && \
	docker compose --env-file env -d restart loki-gateway && \
	docker compose --env-file env -d restart traefik

restart-cadvisor:
	$(MAKE) gpr;
	docker compose --env-file env -d restart pushgateway && \
	docker compose --env-file env -d restart cadvisor && \
	docker compose --env-file env -d restart prometheus && \
	docker compose --env-file env -d restart loki-write && \
	docker compose --env-file env -d restart loki-read && \
	docker compose --env-file env -d restart loki-backend && \
	docker compose --env-file env -d restart grafana && \
	docker compose --env-file env -d restart grafana && \
	docker compose --env-file env -d restart minio && \
	docker compose --env-file env -d restart loki-gateway && \
	docker compose --env-file env -d restart traefik
	$(MAKE) logs;

restart-pihole:
	$(MAKE) gpr;
	docker compose --env-file env -d restart pihole
	$(MAKE) logs;

stop:
	docker compose --env-file env stop pushgateway
	docker compose --env-file env stop cadvisor
	docker compose --env-file env stop prometheus
	docker compose --env-file env stop loki-write
	docker compose --env-file env stop loki-read
	docker compose --env-file env stop loki-backend
	docker compose --env-file env stop grafana
	docker compose --env-file env stop promtail
	docker compose --env-file env stop minio
	docker compose --env-file env stop loki-gateway
	docker compose --env-file env stop traefik


start:
	docker compose --env-file env -d start pushgateway
	docker compose --env-file env -d start cadvisor
	docker compose --env-file env -d start prometheus
	docker compose --env-file env -d start loki-write
	docker compose --env-file env -d start loki-read
	docker compose --env-file env -d start loki-backend
	docker compose --env-file env -d start grafana
	docker compose --env-file env -d start promtail
	docker compose --env-file env -d restart grafana
	docker compose --env-file env -d start minio
	docker compose --env-file env -d start loki-gateway
	docker compose --env-file env -d start traefik

lint:
	promtool check rules prometheus/alerts.yml
	promtool check rules prometheus/rules.yml

logs-loki-backend:
	docker compose --env-file env logs -f --tail=50 loki-backend

logs-loki-write:
	docker compose --env-file env logs -f --tail=50 loki-write

logs-loki-read:
	docker compose --env-file env logs -f --tail=50 loki-read

logs-prometheus:
	docker compose --env-file env logs -f --tail=50 prometheus

logs-grafana:
	docker compose --env-file env logs -f --tail=50 grafana

logs:
	docker compose --env-file env logs -f --tail=50 | grep -v "syslog-ng" | grep -v "pve-exporter" | ccze -A
