# -*- coding: utf-8 -*-
# SOURCE: https://github.com/autopilotpattern/jenkins/blob/master/makefile
MAKEFLAGS += --warn-undefined-variables
# .SHELLFLAGS := -eu -o pipefail

# SOURCE: https://github.com/luismayta/zsh-servers-functions/blob/b68f34e486d6c4a465703472e499b1c39fe4a26c/Makefile
# Configuration.
SHELL = /bin/bash
ROOT_DIR = $(shell pwd)

MAKE := make

gpr:
	git pull --rebase

restart:
	docker compose --env-file env restart pushgateway
	docker compose --env-file env restart prometheus && \
	docker compose --env-file env restart loki-write && \
	docker compose --env-file env restart loki-read && \
	docker compose --env-file env restart loki-backend && \
	docker compose --env-file env restart grafana && \
	docker compose --env-file env restart promtail && \
	docker compose --env-file env restart grafana && \
	docker compose --env-file env restart minio && \
	docker compose --env-file env restart loki-gateway && \
	docker compose --env-file env restart traefik

restart-cadvisor:
	$(MAKE) gpr;
	docker compose --env-file env restart pushgateway && \
	docker compose --env-file env restart cadvisor && \
	docker compose --env-file env restart prometheus && \
	docker compose --env-file env restart loki-write && \
	docker compose --env-file env restart loki-read && \
	docker compose --env-file env restart loki-backend && \
	docker compose --env-file env restart grafana && \
	docker compose --env-file env restart grafana && \
	docker compose --env-file env restart minio && \
	docker compose --env-file env restart loki-gateway && \
	docker compose --env-file env restart traefik
	$(MAKE) logs;

restart-pihole:
	$(MAKE) gpr;
	docker compose --env-file env restart pihole
	$(MAKE) logs;

stop:
	docker compose --env-file env stop pushgateway
	docker compose --env-file env stop cadvisor
	docker compose --env-file env stop prometheus
	docker compose --env-file env stop loki-write
	docker compose --env-file env stop loki-read
	docker compose --env-file env stop loki-backend
	docker compose --env-file env stop grafana
	docker compose --env-file env stop promtail
	docker compose --env-file env stop minio
	docker compose --env-file env stop loki-gateway
	docker compose --env-file env stop traefik


start:
	docker compose -d --env-file env start pushgateway
	docker compose -d --env-file env start cadvisor
	docker compose -d --env-file env start prometheus
	docker compose -d --env-file env start loki-write
	docker compose -d --env-file env start loki-read
	docker compose -d --env-file env start loki-backend
	docker compose -d --env-file env start grafana
	docker compose -d --env-file env start promtail
	docker compose -d --env-file env restart grafana
	docker compose -d --env-file env start minio
	docker compose -d --env-file env start loki-gateway
	docker compose -d --env-file env start traefik

lint:
	promtool check rules prometheus/alerts.yml
	promtool check rules prometheus/rules.yml

logs-loki-backend:
	docker compose --env-file env logs -f --tail=50 loki-backend

logs-loki-write:
	docker compose --env-file env logs -f --tail=50 loki-write

logs-loki-read:
	docker compose --env-file env logs -f --tail=50 loki-read

logs-prometheus:
	docker compose --env-file env logs -f --tail=50 prometheus

logs-grafana:
	docker compose --env-file env logs -f --tail=50 grafana

logs:
	docker compose --env-file env logs -f --tail=50 | grep -v "syslog-ng" | grep -v "pve-exporter" | ccze -A

restart-all:
	docker compose stop; docker compose -d up --env-file env

port-53:
	sudo ss -tlnp|grep :53
get-ports:
	sudo ss -upln
	echo "lsof"
	sudo lsof -nP -iUDP

stop-start:
	docker compose --env-file env stop && docker compose --env-file env up -d

cp-dnsmaq-conf:
	docker cp pihole/dnsmasq.d/02-systemd-override.conf pihole_dnsmasq:/etc/dnsmasq.d/02-systemd-override.conf

network-manager-show:
	sudo nmcli c show

restart-quick:
	git pull --rebase; docker compose --env-file env stop && sleep 100 && docker compose --env-file env up --build -d

get-docker-logs:
	sudo systemctl status --full --no-pager pihole-FTL.service
	sudo -u pihole pihole-FTL -f | ccze -A

# SOURCE: https://ubuntu.com/core/docs/networkmanager/exploring-network-status
network-status:
	echo -e "Show the status of devices known to NetworkManager:\n\n"
	sudo nmcli d
	echo -e "To show the current status of each of NetworkManager's connections:\n\n"
	sudo nmcli c

litecli:
	docker exec -it pihole bash -c litecli --help

# NOTE: https://github.com/systemd/systemd/issues/13432
netplan-apply:
	sudo systemctl status NetworkManager.service
	sudo mkdir -p /etc/systemd/resolved.conf.d
	sudo sh -c 'echo "[Resolve]" > /etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo sh -c 'echo "DNSStubListener=no" >> /etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo sh -c 'echo "DNS={{ prometheus_server_ip }}" >> /etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo sh -c 'echo "FallbackDNS=" >> /etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo sh -c 'echo "Domains=~." >> /etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo sh -c 'echo "DNSSEC=no" >> /etc/systemd/resolved.conf.d/disable-stub.conf'
	echo -e "\n\n"
	cat '/etc/systemd/resolved.conf.d/disable-stub.conf'
	sudo systemctl daemon-reload
	sudo systemctl restart systemd-resolved
	docker cp pihole/dnsmasq.d/02-systemd-override.conf pihole:/etc/dnsmasq.d/02-systemd-override.conf
	sudo ss -tlnp|grep :53
	@echo ""
	sudo cp -av pihole/etc/netplan/02-pihole.yaml /etc/netplan/01-network-manager-all.yaml
	sudo systemctl restart systemd-resolved
	# sudo service systemd-resolved restart
	sudo systemctl restart NetworkManager
	sudo resolvectl flush-caches
	sudo resolvectl status
	sleep 60
	sudo netplan generate
	sudo netplan apply
	sleep 30
	sudo ss -tlnp|grep :53
	@echo ""
	sudo resolvectl statistics
	sudo resolvectl status
	ping -c 1 google.com
	sudo journalctl -f | grep -v unbound_exporter | ccze -A

# SOURCE: https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
generate-pass:
	docker run --rm httpd:2.4-alpine htpasswd -nbB admin password | cut -d ":" -f 2 | sed 's/\$/\$\$/g'

journal-networkd:
	sudo journalctl -b -u systemd-networkd | ccze -A

journal-resolved:
	sudo journalctl -b -u systemd-resolved | ccze -A
